export CUDA_VISIBLE_DEVICES=2
cd ..
python predict.py\
    --saved_model ./checkpoints/unet_fix_bug/CP_best.pth\
    --input_dir ./data/test_img\
    --output_dir ./output\
    --mask_dir ./data/test_label\
    --mask_threshold 0.5\
    --model_name unet